# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diffusion.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 437)
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sourceListWidget = QtWidgets.QListWidget(Dialog)
        self.sourceListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sourceListWidget.setObjectName("sourceListWidget")
        self.verticalLayout.addWidget(self.sourceListWidget)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 4, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.removeError = QtWidgets.QToolButton(Dialog)
        self.removeError.setArrowType(QtCore.Qt.LeftArrow)
        self.removeError.setObjectName("removeError")
        self.gridLayout.addWidget(self.removeError, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.errorListWidget = QtWidgets.QListWidget(Dialog)
        self.errorListWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.errorListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.errorListWidget.setObjectName("errorListWidget")
        self.gridLayout.addWidget(self.errorListWidget, 1, 1, 3, 1)
        self.addError = QtWidgets.QToolButton(Dialog)
        self.addError.setArrowType(QtCore.Qt.RightArrow)
        self.addError.setObjectName("addError")
        self.gridLayout.addWidget(self.addError, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RTListWidget = QtWidgets.QListWidget(Dialog)
        self.RTListWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.RTListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.RTListWidget.setObjectName("RTListWidget")
        self.gridLayout_2.addWidget(self.RTListWidget, 1, 1, 4, 1)
        self.addRT = QtWidgets.QToolButton(Dialog)
        self.addRT.setArrowType(QtCore.Qt.RightArrow)
        self.addRT.setObjectName("addRT")
        self.gridLayout_2.addWidget(self.addRT, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.removeRT = QtWidgets.QToolButton(Dialog)
        self.removeRT.setArrowType(QtCore.Qt.LeftArrow)
        self.removeRT.setObjectName("removeRT")
        self.gridLayout_2.addWidget(self.removeRT, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.addParticipant = QtWidgets.QToolButton(Dialog)
        self.addParticipant.setArrowType(QtCore.Qt.RightArrow)
        self.addParticipant.setObjectName("addParticipant")
        self.gridLayout_3.addWidget(self.addParticipant, 1, 0, 1, 1)
        self.participantListWidget = QtWidgets.QListWidget(Dialog)
        self.participantListWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.participantListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.participantListWidget.setObjectName("participantListWidget")
        self.gridLayout_3.addWidget(self.participantListWidget, 1, 1, 2, 1)
        self.removeParticipant = QtWidgets.QToolButton(Dialog)
        self.removeParticipant.setArrowType(QtCore.Qt.LeftArrow)
        self.removeParticipant.setObjectName("removeParticipant")
        self.gridLayout_3.addWidget(self.removeParticipant, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        self.conditionListWidget = QtWidgets.QListWidget(Dialog)
        self.conditionListWidget.setObjectName("conditionListWidget")
        self.gridLayout_4.addWidget(self.conditionListWidget, 1, 1, 4, 1)
        self.removeCondition = QtWidgets.QToolButton(Dialog)
        self.removeCondition.setArrowType(QtCore.Qt.LeftArrow)
        self.removeCondition.setObjectName("removeCondition")
        self.gridLayout_4.addWidget(self.removeCondition, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        self.addCondition = QtWidgets.QToolButton(Dialog)
        self.addCondition.setArrowType(QtCore.Qt.RightArrow)
        self.addCondition.setObjectName("addCondition")
        self.gridLayout_4.addWidget(self.addCondition, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_5.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.label.setBuddy(self.sourceListWidget)
        self.label_3.setBuddy(self.errorListWidget)
        self.label_4.setBuddy(self.RTListWidget)
        self.label_2.setBuddy(self.participantListWidget)
        self.label_5.setBuddy(self.conditionListWidget)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sourceListWidget, self.removeError)
        Dialog.setTabOrder(self.removeError, self.errorListWidget)
        Dialog.setTabOrder(self.errorListWidget, self.RTListWidget)
        Dialog.setTabOrder(self.RTListWidget, self.removeCondition)
        Dialog.setTabOrder(self.removeCondition, self.conditionListWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Behavioral data diffusion analysis"))
        self.label.setText(_translate("Dialog", "Available variables"))
        self.label_3.setText(_translate("Dialog", "Error"))
        self.label_4.setText(_translate("Dialog", "Reaction time (in sec)"))
        self.label_2.setText(_translate("Dialog", "Participant"))
        self.label_5.setText(_translate("Dialog", "Condition(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
