# Form implementation generated from reading ui file 'preferences.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 204)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.lang_combo_box = QtWidgets.QComboBox(parent=Dialog)
        self.lang_combo_box.setObjectName("lang_combo_box")
        self.gridLayout_3.addWidget(self.lang_combo_box, 0, 1, 1, 1)
        self.error_combo_box = QtWidgets.QComboBox(parent=Dialog)
        self.error_combo_box.setObjectName("error_combo_box")
        self.gridLayout_3.addWidget(self.error_combo_box, 5, 1, 1, 1)
        self.theme_combo_box = QtWidgets.QComboBox(parent=Dialog)
        self.theme_combo_box.setObjectName("theme_combo_box")
        self.gridLayout_3.addWidget(self.theme_combo_box, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.image_combo_box = QtWidgets.QComboBox(parent=Dialog)
        self.image_combo_box.setObjectName("image_combo_box")
        self.gridLayout_3.addWidget(self.image_combo_box, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.p_value_combo_box = QtWidgets.QComboBox(parent=Dialog)
        self.p_value_combo_box.setObjectName("p_value_combo_box")
        self.gridLayout_3.addWidget(self.p_value_combo_box, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Help|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_2, 9, 0, 1, 1)
        self.label_3.setBuddy(self.theme_combo_box)
        self.label_2.setBuddy(self.error_combo_box)
        self.label_5.setBuddy(self.image_combo_box)
        self.label.setBuddy(self.lang_combo_box)
        self.label_4.setBuddy(self.p_value_combo_box)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lang_combo_box, self.theme_combo_box)
        Dialog.setTabOrder(self.theme_combo_box, self.image_combo_box)
        Dialog.setTabOrder(self.image_combo_box, self.p_value_combo_box)
        Dialog.setTabOrder(self.p_value_combo_box, self.error_combo_box)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.label_3.setText(_translate("Dialog", "Chart theme"))
        self.label_6.setText(_translate("Dialog", "Restart CogStat to use the new language settings"))
        self.label_2.setText(_translate("Dialog", "Detailed error message"))
        self.label_5.setText(_translate("Dialog", "Image format"))
        self.label.setText(_translate("Dialog", "Language"))
        self.label_4.setText(_translate("Dialog", "P value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
