# These are the settings that can be changed from Preferences in the GUI
[Preferences] # configparser requires a category
language = en # available languages can be found at https://github.com/cogstat/cogstat/tree/devel/cogstat/locale
theme = seaborn-muted, seaborn-v0_8-muted # available matplotlib themes can be used
image_format = png # png or svg
p_value_format = apa # apa or scientific
detailed_error_message = False # True or False
